[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "shushos-target.json"

[dependencies]
bootloader = "0.9.8"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
